name = "Revelation++"
author = "Milchmann77"
version = "26w41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddc14d63ebdb1e2576be961dc429ac59c31370f60deac8810de84b1a114de57b"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
