name = "Revelation++"
author = "Milchmann77"
version = "26w41d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8908d5d0ca8a956b87b9d1311d23ab40109b8a5740e138260e90b8909ad42ea"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
